services:
  backend:
    build:
      context: backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./backend/uploads:/code/uploads
    networks:
      - public
      - private
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: frontend
    ports:
      - "4173:4173"
    networks:
      - public
    depends_on:
      - backend

  db:
    image: mariadb:10.6.4-focal
    container_name: db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - private
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${DATABASE_PASSWORD} || exit 1"]
      interval: 10s
      retries: 3

  add_doctor:
    image: curlimages/curl:latest
    depends_on:
      backend:
        condition: service_started
    entrypoint: ["sh", "-c", "sleep 10 && curl -X POST http://backend:8000/doctors -H 'Content-Type: application/x-www-form-urlencoded' -d 'firstname=Will&lastname=Smith&email=ws@o.ai&password=123' || true"]
    networks:
      - public
      - private

networks:
  public:
  private:

volumes:
  db-data:
